language: php

php:
  - "7.0"
  - 7.1

build:
  ci:
    - sudo apt-get install libxml2-utils
    - find . -path ./vendor -prune -o -name '*.xml' -print -exec xmllint --noout {} \;
    - composer self-update
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
    - composer install --no-interaction --prefer-dist
    - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
    - php vendor/bin/parallel-lint --exclude vendor .
    - php vendor/bin/phpcs --standard=vendor/mygento/coding-standard/Mygento-Mage2 .
    - php vendor/bin/phpmd . text cleancode,codesize,controversial,design,naming,unusedcode vendor/mygento/coding-standard/Mygento-Mage2/phpmd.xml --exclude vendor
env:
  - secure: uglEqQjwB7sc3R8AE7fSVXzkii1H/wOHRNtO8tJYZei9Nzr9Z6LeTuYBfDUsinVgEXruXxfOo85z2goYRHFK9oS9JSHJz9RzvLEItCiK2YYKRDStLE9ceMAf5N7IqKGJXnGmN+toph0MP/5WQB/M68G6HGJm3rBdTxfURZLUOuakNRJ4VHh9kH4De/m3RdYXpPId0u4Xw88l1/4S0KFCC9SS68GQ9A9+RexejES07/AHhnOUyZOXdIdue94YhYx8d5COo0n/PME6ialcRM+FOK2tabskBkrGG4q7L7XH1sFCv/98V9Fe57SphqGjXt1eNXUiB1eFLFqKX8IEhF6/DA==